### ISSUE TITLE
Feature 602 Linked Data: Relationships and Data Models can no longer be run 

### ISSUE THREAD

**Issue by bobeal** [Amybough/Tests#39]
I was trying to run the feature `602.ngsild.RelationshipsAndDataModels` but @jason-fox recently removed all the services from this tutorial (https://github.com/FIWARE/tutorials.Relationships-Linked-Data/commit/9163a7bf5b6304716a1cad0c8d62dc89ccc07a99) so the feature can no longer be run.

Are there plans to migrate it or will it be dropped?

**Comment by jason-fox** [comment]
As stated on the `README`:

> To run this  tutorial for **NGSI-v2** developers, use the `NGSI-v2` branch.
>
> ```
> git clone https://github.com/FIWARE/tutorials.Relationships-Linked-Data.git
> cd tutorials.Relationships-Linked-Data
> git checkout NGSI-v2
> 
> ./services create
> ./services start
> ```


The  **NGSI-LD** tutorials have always only been available on the `ngsi-ld` branch.
Whereas previously the  **NGSI-v2** were available on both `master` and `ngsi-v2` 
(since there were a lot more of them than LD) - this was giving the false impression that
v2 was the default. The current set-up places v2 and LD on an equal footing and explains
the proper use-case for each variant.

Running `./services start` on `master`  now gives an informational message only.

**Comment by jason-fox** [comment]
The reasoning behind this is that I've seen users checking out a tutorial to learn NGSI-LD, forgetting to switch to the correct branch and then the tutorial text  doesn't line up with the commands.

**Comment by bobeal** [comment]
Agree with the equal footing but since there is no longer a `ngsi-ld` branch in the repository of the tutorial (only a `ngsiv2` one)...

**Comment by jason-fox** [comment]
That tutorial is **Smart Supermarket** which is `ngsi-v2` - or rather to quote from the `master` README:

> To run this NGSI-LD tutorial for NGSI-v2 developers, use the NGSI-v2 branch.

It wa an early attempt to discuss the necessary minimal changes to switch a v2 system to run as LD and deliberately minimizes the role of  `@context` - the proper `ngsi-ld` **Smart Farm** tutorials are instead user-context driven, which is the right way to design an LD system.
